### ISSUE TITLE
How much data did you use to train the model?

### ISSUE THREAD

**Issue by Charlottecuc** [yl4579/AuxiliaryASR#1]
Hi. Thank you for you great work!
I was wondering how much data did you use to train the model, and did you augment the data? 
I notice that you put the LJSpeech dataset here as an example, but the sample rate of LJ is 22050khz, so I think it is not the data you actually used when training the model...?

**Comment by yl4579** [comment]
I used [LibriTTS](https://research.google/tools/datasets/libri-tts/), a subset of LibriSpeech with a higher sampling rate (24kHz).
