### ISSUE TITLE
how to train for mandarin asr?

### ISSUE THREAD

**Issue by MMMMichaelzhang** [yl4579/AuxiliaryASR#2]
if I want to train mandarin asr,dict is like this[dict.txt](https://github.com/yl4579/AuxiliaryASR/files/8883881/dict.txt),and I use [g2pM](https://github.com/kakaobrain/g2pM) as phonemizer,and train.txt is like this:
SSB06930002.wav | 武 wu3 术 shu4 始 shi3 终 zhong1 被 bei4 看 kan4 作 zuo4 我 wo3 国 guo2 的 de5 国 guo2 粹 cui4 | 0
I don't know how to change my format（dict.txt \train.txt） to suit this project, and how to change it in meldataset. can you help me? Thank you very much

**Comment by MMMMichaelzhang** [comment]
[dict.txt](https://github.com/yl4579/AuxiliaryASR/files/8883881/dict.txt)

**Comment by Charlottecuc** [comment]
You shouldn't put hanzi characters in train.txt, and the pinyin sequences should be transformed into phoneme sequences.

**Comment by yl4579** [comment]
I believe it should be like `SSB06930002.wav | wu shu shi zhong bei kan zuo wo guo de guo cui | 0`. You don't want the tones nor the Chinese characters here, the ASR model should only be used for phonemes.

**Comment by MMMMichaelzhang** [comment]
> 

Thanks ,it helps a lot!!! I am still confused about dict.txt for mandarin.my fomart is like this:
"a",1
"ao",2
"an",3
"w",4
"t",5
"d",6
"n",7
or：
“wa”,1
"ta",2
"na",3
"tao",4
"dao",5
"wan",6
"tan",7
which one should i use? @yl4579 @Charlottecuc

**Comment by MMMMichaelzhang** [comment]
I use g2pM as phonemizer,
>>> sentence = "然而，他红了20年以后，他竟退出了大家的视线。"
>>> model(sentence, tone=False, char_split=False)
['ran', 'er', '，', 'ta', 'hong', 'le', '2', '0', 'nian', 'yi', 'hou', '，', 'ta', 'jing', 'tui', 'chu', 'le', 'da', 'jia', 'de', 'shi', 'xian', '。']
so the dict.txt 's format should be like this?
“wa”,1
"ta",2
"na",3
"tao",4
"dao",5
"wan",6
"tan",7
@yl4579 @Charlottecuc

**Comment by Charlottecuc** [comment]
> I use g2pM as phonemizer,
> 
> > > > sentence = "然而，他红了20年以后，他竟退出了大家的视线。"
> > > > model(sentence, tone=False, char_split=False)
> > > > ['ran', 'er', '，', 'ta', 'hong', 'le', '2', '0', 'nian', 'yi', 'hou', '，', 'ta', 'jing', 'tui', 'chu', 'le', 'da', 'jia', 'de', 'shi', 'xian', '。']
> > > > so the dict.txt 's format should be like this?
> > > > “wa”,1
> > > > "ta",2
> > > > "na",3
> > > > "tao",4
> > > > "dao",5
> > > > "wan",6
> > > > "tan",7
> > > > @yl4579 @Charlottecuc



> > 
> 
> Thanks ,it helps a lot!!! I am still confused about dict.txt for mandarin.my fomart is like this: "a",1 "ao",2 "an",3 "w",4 "t",5 "d",6 "n",7 or： “wa”,1 "ta",2 "na",3 "tao",4 "dao",5 "wan",6 "tan",7 which one should i use? @yl4579 @Charlottecuc

I use the first type of format because I don't want too many tokens in my dictionary (which is quite common when training Mandarin TTS models). Besides, I suggest you transform "20" to "er sh i" in this context.

**Comment by Moonmore** [comment]
> I believe it should be like `SSB06930002.wav | wu shu shi zhong bei kan zuo wo guo de guo cui | 0`. You don't want the tones (that should be handled by the F0 model) nor the Chinese characters (they aren't phonemes) here. The ASR model should only be used for phonemes.

@yl4579 I would like to ask if tones information is not added to the asr model training, then how to align the text encoder and mel. For example: (你好 ->ni3 hao3 -> n i3 h ao3), (n i h ao).

**Comment by yl4579** [comment]
@Moonmore You do not need tones for this. The pre-trained aligner in StyleTTS and StyleTTS 2 repo was already trained on Mandarin (AiShell) without tones. The conversion table between IPA and pinyin is here: https://github.com/yl4579/StyleTTS/issues/10#issuecomment-1407788234
Once you use this table to convert pinyin to IPA, you can directly use the pre-trained aligner and you don't need to train it yourself. However, if you want to train it yourself on pinyin, you do not need to include tones.

**Comment by Moonmore** [comment]
> @Moonmore You do not need tones for this. The pre-trained aligner in StyleTTS and StyleTTS 2 repo was already trained on Mandarin (AiShell) without tones. The conversion table between IPA and pinyin is here: [yl4579/StyleTTS#10 (comment)](https://github.com/yl4579/StyleTTS/issues/10#issuecomment-1407788234) Once you use this table to convert pinyin to IPA, you can directly use the pre-trained aligner and you don't need to train it yourself. However, if you want to train it yourself on pinyin, you do not need to include tones.

@yl4579  thanks for your reply. I successfully used pinyin to train the model.
