### ISSUE TITLE
how to make word_index_dict.txt

### ISSUE THREAD

**Issue by hai8023** [yl4579/AuxiliaryASR#3]
I have a little immature question, how to make word_index_dict.txt about Mandarin?

**Comment by hai8023** [comment]
My understanding is to write all the appearing phonemes into the txt file and correspond to an id, is my understanding correct?

**Comment by Charlottecuc** [comment]
I guess the first five tokens should be "<pad>", "<sos>", "<eos>", "<unk>" and blank. e.g. https://github.com/yl4579/AuxiliaryASR/blob/5cb3ee46c4839d96d50c8ad9b3f378b1d7f06df7/models.py#L106

**Comment by hai8023** [comment]
Thanks, got it
