### ISSUE TITLE
why mel_spectrogam feature extracting using only MEL_PARAMS here?

### ISSUE THREAD

**Issue by superhg** [yl4579/AuxiliaryASR#6]
Hi, why mel_spectrogam feature extracting using only MEL_PARAMS? why SPECT_PARAMS not used?

https://github.com/yl4579/AuxiliaryASR/blob/7bca68a111545a3e92d7e7f88a0639fef87ce7ea/meldataset.py#L50

**Comment by superhg** [comment]
another question, can I train data with 16000 sampling rate just modifying SPECT_PARAMS ?

**Comment by yl4579** [comment]
Because it was a mistake from the very beginning. See https://github.com/yl4579/StarGANv2-VC/issues/10. I have fixed that part, but I don't think it'll make too much difference. The only thing you have to work out is the vocoder.

**Comment by yl4579** [comment]
As for the 16k Hz sampling rate, I think it should work, as long as your application (VC or TTS) also uses 16k Hz and your vocoder is trained with the same setting.
